# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160418_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 18, 18, 58, 56, 991040, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
