# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
